import itertools
import re


def convert(string: str) -> str:
    # Tutorial
    tmp = re.sub("\\s*\\(tutorial\\)\\s*", "1 \\{\\{P|Basic Zombie|2}}", re.sub("\\s*\\(tutorial_armor1\\)\\s*", "2 \\{\\{P|Conehead Zombie|2}}", re.sub("\\s*\\(tutorial_armor2\\)\\s*", "3 \\{\\{P|Buckethead Zombie|2}}", re.sub("\\s*\\(tutorial_armor4\\)\\s*", "4 \\{\\{P|Brickhead Zombie|2}}", re.sub("\\s*\\(modern_newspaper\\)\\s*", "131 \\{\\{P|Newspaper Zombie|2}}", re.sub("\\s*\\(newspaper_veteran\\)\\s*", "131 \\{\\{P|Newspaper Zombie|2}}", re.sub("\\s*\\(modern_balloon\\)\\s*", "95 \\{\\{P|Balloon Zombie|2}}", re.sub("\\s*\\(tutorial_balloon\\)\\s*", "95 \\{\\{P|Balloon Zombie|2}}", re.sub("\\s*\\(tutorial_gargantuar\\)\\s*", "5 \\{\\{P|Gargantuar|2}}", re.sub("\\s*\\(tutorial_imp\\)\\s*", "6 \\{\\{P|Imp|2}}", re.sub("\\s*\\(mega_gargantuar\\)\\s*", "132 \\{\\{P|Mega Gargantuar|2}}", re.sub("\\s*\\(conehead_imp\\)\\s*", "133 \\{\\{P|Conehead Imp|2}}", string))))))))))))
    # Egypt
    tmp1 = re.sub("\\(ra\\)", ";<sup>0</sup>;13;{{P|Ra Zombie|2}}", re.sub("\\(mummy\\)", ";<sup>0</sup>;7;{{P|Mummy Zombie|2}}", re.sub("\\(mummy_armor1\\)", ";<sup>0</sup>;8;{{P|Conehead Mummy|2}}", re.sub("\\(mummy_armor2\\)", ";<sup>0</sup>;9;{{P|Buckethead Mummy|2}}", re.sub("\\(camel_onehump\\)", ";<sup>0</sup>;14;{{P|Camel Zombies|2}}", re.sub("\\(explorer\\)", ";<sup>0</sup>;15;{{P|Explorer Zombie|2}}", re.sub("\\(egypt_imp\\)", ";<sup>0</sup>;12;{{P|Imp Mummy|2}}", re.sub("\\(mummy_armor4\\)", ";<sup>0</sup>;10;{{P|Pyramid-Head Zombie|2}}", re.sub("\\(egypt_gargantuar\\)", ";<sup>0</sup>;11;{{P|Mummified Gargantuar|2}}", re.sub("\\(pharaoh\\)", ";<sup>0</sup>;16;{{P|Pharaoh Zombie|2}}", re.sub("\\(tomb_raiser\\)", ";<sup>0</sup>;17;{{P|Tomb Raiser Zombie|2}}", re.sub("\\(explorer_veteran\\)", ";<sup>0</sup>;18;{{P|Torchlight Zombie|2}}", re.sub("\\(cleopatra_zombie\\)", ";<sup>0</sup>;19;{{P|Cleopatra Zombie|2}}", tmp)))))))))))))
    # Dark
    tmp2 = re.sub("\\(dark\\)", ";<sup>0</sup>;34;{{P|Peasant Zombie|2}}", re.sub("\\(dark_armor1\\)", ";<sup>0</sup>;35;{{P|Conehead Peasant|2}}", re.sub("\\(dark_armor2\\)", ";<sup>0</sup>;36;{{P|Buckethead Peasant|2}}", re.sub("\\(dark_armor3\\)", ";<sup>0</sup>;37;{{P|Knight Zombie|2}}", re.sub("\\(dark_juggler\\)", ";<sup>0</sup>;43;{{P|Jester Zombie|2}}", re.sub("\\(dark_wizard\\)", ";<sup>0</sup>;41;{{P|Wizard Zombie|2}}", re.sub("\\(dark_king\\)", ";<sup>0</sup>;42;{{P|Zombie King|2}}", re.sub("\\(dark_imp_dragon\\)", ";<sup>0</sup>;40;{{P|Imp Dragon Zombie|2}}", re.sub("\\(dark_gargantuar\\)", ";<sup>0</sup>;38;{{P|Dark Ages Gargantuar|2}}", re.sub("\\(dark_imp\\)", ";<sup>0</sup>;39;{{P|Imp Monk Zombie|2}}", re.sub("\\(night_camel\\)", ";<sup>0</sup>;44;{{P|Shadow Zombie|2}}", tmp1)))))))))))
    # Future
    tmp3 = re.sub("\\s*\\(future\\)\\s*", "105 \\{\\{Future Zombie|2}}", re.sub("\\s*\\(future_armor1\\)\\s*", "106 \\{\\{Future Conehead Zombie|2}}", re.sub("\\s*\\(future_armor2\\)\\s*", "107 \\{\\{Future Buckethead Zombie|2}}", re.sub("\\s*\\(future_jetpack\\)\\s*", "111 \\{\\{Jetpack Zombie|2}}", re.sub("\\s*\\(future_protector\\)\\s*", "110 \\{\\{Shield Zombie|2}}", re.sub("\\s*\\(mech_cone\\)\\s*", "112 \\{\\{Robo-Cone Zombie|2}}", re.sub("\\s*\\(disco_mech\\)\\s*", "113 \\{\\{Disco-tron 3000|2}}", re.sub("\\s*\\(future_jetpack_disco\\)\\s*", "114 \\{\\{Disco Jetpack Zombie|2}}", re.sub("\\s*\\(football_mech\\)\\s*", "115 \\{\\{Mecha-Football Zombie|2}}", re.sub("\\s*\\(future_gargantuar\\)\\s*", "108 \\{\\{Gargantuar Prime|2}}", re.sub("\\s*\\(future_imp\\)\\s*", "109 \\{\\{Bug Bot Imp|2}}", tmp2)))))))))))
    # Ice
    tmp4 = re.sub("\\s*\\(iceage\\)\\s*", "58 \\{\\{Cave Zombie|2}}", re.sub("\\s*\\(iceage_armor1\\)\\s*", "59 \\{\\{Cave Conehead Zombie|2}}", re.sub("\\s*\\(iceage_armor2\\)\\s*", "60 \\{\\{Cave Buckethead Zombie|2}}", re.sub("\\s*\\(iceage_armor3\\)\\s*", "61 \\{\\{Blockhead Zombie|2}}", re.sub("\\s*\\(iceage_hunter\\)\\s*", "65 \\{\\{Hunter Zombie|2}}", re.sub("\\s*\\(iceage_dodo\\)\\s*", "64 \\{\\{Dodo Rider Zombie|2}}", re.sub("\\s*\\(iceage_troglobite_1block\\)\\s*", "66 \\{\\{Troglobite|2}}", re.sub("\\s*\\(iceage_troglobite_2block\\)\\s*", "66 \\{\\{Troglobite|2}}", re.sub("\\s*\\(iceage_troglobite\\)\\s*", "66 \\{\\{Troglobite|2}}", re.sub("\\s*\\(iceage_weaselhoarder\\)\\s*", "67 \\{\\{Weasel Hoarder|2}}", re.sub("\\s*\\(iceage_weasel\\)\\s*", "68 \\{\\{Ice Weasel|2}}", re.sub("\\s*\\(iceage_gargantuar\\)\\s*", "62 \\{\\{Sloth Gargantuar|2}}", re.sub("\\s*\\(iceage_imp\\)\\s*", "63 \\{\\{Yeti Imp|2}}", re.sub("\\s*\\(hellbird\\)\\s*", "69 \\{\\{Zombie Nether Dodo|2}}", tmp3))))))))))))))
    # Lost
    tmp5 = re.sub("\\s*\\(lostcity\\)\\s*", "20 \\{\\{P|Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_armor1\\)\\s*", "21 \\{\\{P|Conehead Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_armor2\\)\\s*", "22 \\{\\{P|Buckethead Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_excavator\\)\\s*", "32 \\{\\{P|Excavator Zombie|2}}", re.sub("\\s*\\(lostcity_jane\\)\\s*", "25 \\{\\{P|Parasol Zombie|2}}", re.sub("\\s*\\(lostcity_lostpilot\\)\\s*", "26 \\{\\{P|Lost Pilot Zombie|2}}", re.sub("\\s*\\(lostcity_bug\\)\\s*", "27 \\{\\{P|Bug Zombie|2}}", re.sub("\\s*\\(lostcity_bug_armor1\\)\\s*", "28 \\{\\{P|Bug Conehead Zombie|2}}", re.sub("\\s*\\(lostcity_bug_armor2\\)\\s*", "29 \\{\\{P|Bug Buckethead Zombie|2}}", re.sub("\\s*\\(lostcity_impporter\\)\\s*", "31 \\{\\{P|Imp Porter|2}}", re.sub("\\s*\\(lostcity_relichunter\\)\\s*", "33 \\{\\{P|Relic Hunter Zombie|2}}", re.sub("\\s*\\(lostcity_crystalskull\\)\\s*", "30 \\{\\{P|Turquoise Skull Zombie|2}}", re.sub("\\s*\\(lostcity_gargantuar\\)\\s*", "23 \\{\\{P|Porter Gargantuar|2}}", re.sub("\\s*\\(lostcity_imp\\)\\s*", "24 \\{\\{P|Lost City Imp Zombie|2}}", re.sub("\\s*\\(lostcity_mime\\)\\s*", "14\\{\\{P|Mime Zombie|2}}", tmp4)))))))))))))))
    # Jurassic
    tmp6 = re.sub("\\s*\\(dino\\)\\s*", "96 \\{\\{P|Jurassic Zombie|2}}", re.sub("\\s*\\(dino_armor1\\)\\s*", "97 \\{\\{P|Jurassic Conehead|2}}", re.sub("\\s*\\(dino_armor2\\)\\s*", "98 \\{\\{P|Jurassic Buckethead|2}}", re.sub("\\s*\\(dino_armor3\\)\\s*", "99 \\{\\{P|Jurassic Fossilhead|2}}", re.sub("\\s*\\(dino_armor4\\)\\s*", "100 \\{\\{P|Amberhead Zombie|2}}", re.sub("\\s*\\(dino_bully\\)\\s*", "103 \\{\\{P|Jurassic Bully|2}}", re.sub("\\s*\\(dino_bully_veteran\\)\\s*", "103 \\{\\{P|Jurassic Bully|2}}", re.sub("\\s*\\(dino_gargantuar\\)\\s*", "101 \\{\\{P|Jurassic Gargantuar|2}}", re.sub("\\s*\\(dino_imp\\)\\s*", "102 \\{\\{P|Jurassic Imp|2}}", re.sub("\\s*\\(modern_superfanimp\\)\\s*", "104 \\{\\{P|Flint imp|2}}", tmp5))))))))))
    # Neon
    tmp7 = re.sub("\\s*\\(eighties\\)\\s*", "116 \\{\\{P|Neon Zombie|2}}", re.sub("\\s*\\(eighties_armor1\\)\\s*", "117 \\{\\{P|Neon Conehead|2}}", re.sub("\\s*\\(eighties_armor2\\)\\s*", "118 \\{\\{P|Neon Buckethead|2}}", re.sub("\\s*\\(eighties_punk\\)\\s*", "122 \\{\\{P|Punk Zombie|2}}", re.sub("\\s*\\(eighties_glitter\\)\\s*", "121 \\{\\{P|Glitter Zombie|2}}", re.sub("\\s*\\(eighties_mc\\)\\s*", "124 \\{\\{P|MC Zom-B|2}}", re.sub("\\s*\\(eighties_breakdancer\\)\\s*", "129 \\{\\{P|Breakdancer Zombie|2}}", re.sub("\\s*\\(eighties_arcade\\)\\s*", "125 \\{\\{P|Arcade Zombie|2}}", re.sub("\\s*\\(eighties_8bit\\)\\s*", "126 \\{\\{P|8-Bit Zombie|2}}", re.sub("\\s*\\(eighties_8bit_armor1\\)\\s*", "127 \\{\\{P|8-Bit Conehead Zombie|2}}", re.sub("\\s*\\(eighties_8bit_armor2\\)\\s*", "128 \\{\\{P|8-Bit Buckethead Zombie|2}}", re.sub("\\s*\\(eighties_boombox\\)\\s*", "123 \\{\\{P|Boombox Zombie|2}}", re.sub("\\s*\\(eighties_gargantuar\\)\\s*", "119 \\{\\{P|Hair Metal Gargantuar|2}}", re.sub("\\s*\\(eighties_imp\\)\\s*", "120 \\{\\{P|Impunk|2}}", tmp6))))))))))))))
    # Pirate
    tmp8 = re.sub("\\s*\\(pirate\\)\\s*", "45 \\{\\{P|Pirate Zombie|2}}", re.sub("\\s*\\(pirate_armor1\\)\\s*", "46 \\{\\{P|Conehead Pirate|2}}", re.sub("\\s*\\(pirate_armor2\\)\\s*", "47 \\{\\{P|Buckethead Pirate|2}}", re.sub("\\s*\\(pirate_armor4\\)\\s*", "48\\{\\{P|Cannonhead Zombie|2}}", re.sub("\\s*\\(swashbuckler\\)\\s*", "51 \\{\\{P|Swashbuckler Zombie|2}}", re.sub("\\s*\\(seagull\\)\\s*", "54 \\{\\{P|Seagull Zombie|2}}", re.sub("\\s*\\(pelican\\)\\s*", "57 \\{\\{P|Pelican Zombie|2}}", re.sub("\\s*\\(barrelroller\\)\\s*", "52 \\{\\{P|Barrel Roller Zombie|2}}", re.sub("\\s*\\(pirate_barrel\\)\\s*", "53 \\{\\{P|Pirate Barrel|2}}", re.sub("\\s*\\(cannon\\)\\s*", "56 \\{\\{P|Imp Cannon|2}}", re.sub("\\s*\\(pirate_captain\\)\\s*", "55 \\{\\{P|Pirate Captain Zombie|2}}", re.sub("\\s*\\(pirate_gargantuar\\)\\s*", "49 \\{\\{P|Gargantuar Pirate|2}}", re.sub("\\s*\\(pirate_imp\\)\\s*", "50 \\{\\{P|Imp Pirate Zombie|2}}", tmp7)))))))))))))
    # West
    tmp9 = re.sub("\\s*\\(cowboy\\)\\s*", "70 \\{\\{P|Cowboy Zombie|2}}", re.sub("\\s*\\(cowboy_armor1\\)\\s*", "71 \\{\\{P|Conehead Cowboy|2}}", re.sub("\\s*\\(cowboy_armor2\\)\\s*", "72 \\{\\{P|Buckethead Cowboy|2}}", re.sub("\\s*\\(cowboy_armor4\\)\\s*", "73 \\{\\{P|Cart-Head Zombie|2}}", re.sub("\\s*\\(prospector\\)\\s*", "76 \\{\\{P|Prospector Zombie|2}}", re.sub("\\s*\\(piano\\)\\s*", "77 \\{\\{P|Pianist Zombie|2}}", re.sub("\\s*\\(poncho\\)\\s*", "80 \\{\\{P|Vegan Zombie|2}}", re.sub("\\s*\\(poncho_no_plate\\)\\s*", "81 \\{\\{P|Poncho Zombie|2}}", re.sub("\\s*\\(poncho_plate\\)\\s*", "81 \\{\\{P|Poncho Zombie|2}}", re.sub("\\s*\\(chicken_farmer\\)\\s*", "79 \\{\\{P|Chicken Wrangler Zombie|2}}", re.sub("\\s*\\(west_bull\\)\\s*", "78 \\{\\{P|Zombie Bull|2}}", re.sub("\\s*\\(cowboy_gargantuar\\)\\s*", "74 \\{\\{P|Wild West Gargantuar|2}}", re.sub("\\s*\\(west_bullrider\\)\\s*", "75 \\{\\{P|Zombie Bull Rider|2}}", tmp8)))))))))))))
    return tmp9
