import re
import linecache


def convert(string: str) -> str:
    zombies_convert = open('convert.txt', 'r')

    for line in range(len([line.strip("\n") for line in zombies_convert if line != "\n"])):
        zombie = re.sub('\n', '', linecache.getline('convert.txt', line + 1)).split(': ')
        string = re.sub(str(zombie[0]), str(zombie[1]), string)
    # Egypt
    tmp1 = re.sub("\\(mummy\\)", ";<sup>0</sup>;7;{{P|Mummy Zombie|2}}", re.sub("\\(mummy_armor1\\)", ";<sup>0</sup>;8;{{P|Conehead Mummy|2}}", re.sub("\\(mummy_armor2\\)", ";<sup>0</sup>;9;{{P|Buckethead Mummy|2}}", re.sub("\\(camel_onehump\\)", ";<sup>0</sup>;14;{{P|Camel Zombies|2}}", re.sub("\\(explorer\\)", ";<sup>0</sup>;15;{{P|Explorer Zombie|2}}", re.sub("\\(egypt_imp\\)", ";<sup>0</sup>;12;{{P|Imp Mummy|2}}", re.sub("\\(mummy_armor4\\)", ";<sup>0</sup>;10;{{P|Pyramid-Head Zombie|2}}", re.sub("\\(egypt_gargantuar\\)", ";<sup>0</sup>;11;{{P|Mummified Gargantuar|2}}", re.sub("\\(pharaoh\\)", ";<sup>0</sup>;16;{{P|Pharaoh Zombie|2}}", re.sub("\\(tomb_raiser\\)", ";<sup>0</sup>;17;{{P|Tomb Raiser Zombie|2}}", re.sub("\\(explorer_veteran\\)", ";<sup>0</sup>;18;{{P|Torchlight Zombie|2}}", re.sub("\\(cleopatra_zombie\\)", ";<sup>0</sup>;19;{{P|Cleopatra Zombie|2}}", string))))))))))))
    # Dark
    tmp2 = re.sub("\\(dark\\)", ";<sup>0</sup>;34;{{P|Peasant Zombie|2}}", re.sub("\\(dark_armor1\\)", ";<sup>0</sup>;35;{{P|Conehead Peasant|2}}", re.sub("\\(dark_armor2\\)", ";<sup>0</sup>;36;{{P|Buckethead Peasant|2}}", re.sub("\\(dark_armor3\\)", ";<sup>0</sup>;37;{{P|Knight Zombie|2}}", re.sub("\\(dark_juggler\\)", ";<sup>0</sup>;43;{{P|Jester Zombie|2}}", re.sub("\\(dark_wizard\\)", ";<sup>0</sup>;41;{{P|Wizard Zombie|2}}", re.sub("\\(dark_king\\)", ";<sup>0</sup>;42;{{P|Zombie King|2}}", re.sub("\\(dark_imp_dragon\\)", ";<sup>0</sup>;40;{{P|Imp Dragon Zombie|2}}", re.sub("\\(dark_gargantuar\\)", ";<sup>0</sup>;38;{{P|Dark Ages Gargantuar|2}}", re.sub("\\(dark_imp\\)", ";<sup>0</sup>;39;{{P|Imp Monk Zombie|2}}", re.sub("\\(night_camel\\)", ";<sup>0</sup>;44;{{P|Shadow Zombie|2}}", tmp1)))))))))))
    # Future
    tmp3 = re.sub("\\s*\\(future\\)\\s*", ";<sup>0</sup>;105;{{Future Zombie|2}}", re.sub("\\s*\\(future_armor1\\)\\s*", ";<sup>0</sup>;106;{{Future Conehead Zombie|2}}", re.sub("\\s*\\(future_armor2\\)\\s*", ";<sup>0</sup>;107;{{Future Buckethead Zombie|2}}", re.sub("\\s*\\(future_jetpack\\)\\s*", ";<sup>0</sup>;111;{{Jetpack Zombie|2}}", re.sub("\\s*\\(future_protector\\)\\s*", ";<sup>0</sup>;110;{{Shield Zombie|2}}", re.sub("\\s*\\(mech_cone\\)\\s*", ";<sup>0</sup>;112{{Robo-Cone Zombie|2}}", re.sub("\\s*\\(disco_mech\\)\\s*", ";<sup>0</sup>;113;{{Disco-tron 3000|2}}", re.sub("\\s*\\(future_jetpack_disco\\)\\s*", ";<sup>0</sup>;114;{{Disco Jetpack Zombie|2}}", re.sub("\\s*\\(football_mech\\)\\s*", ";<sup>0</sup>;115;{{Mecha-Football Zombie|2}}", re.sub("\\s*\\(future_gargantuar\\)\\s*", ";<sup>0</sup>;108;{{Gargantuar Prime|2}}", re.sub("\\s*\\(future_imp\\)\\s*", ";<sup>0</sup>;109;{{Bug Bot Imp|2}}", tmp2)))))))))))
    # Ice
    tmp4 = re.sub("\\s*\\(iceage\\)\\s*", ";<sup>0</sup>;58;{{Cave Zombie|2}}", re.sub("\\s*\\(iceage_armor1\\)\\s*", ";<sup>0</sup>;59;{{Cave Conehead Zombie|2}}", re.sub("\\s*\\(iceage_armor2\\)\\s*", ";<sup>0</sup>;60;{{Cave Buckethead Zombie|2}}", re.sub("\\s*\\(iceage_armor3\\)\\s*", ";<sup>0</sup>;61;{{Blockhead Zombie|2}}", re.sub("\\s*\\(iceage_hunter\\)\\s*", ";<sup>0</sup>;65;{{Hunter Zombie|2}}", re.sub("\\s*\\(iceage_dodo\\)\\s*", ";<sup>0</sup>;64;{{Dodo Rider Zombie|2}}", re.sub("\\s*\\(iceage_troglobite_1block\\)\\s*", ";<sup>0</sup>;66;{{Troglobite|2}}", re.sub("\\s*\\(iceage_troglobite_2block\\)\\s*", ";<sup>0</sup>;66;{{Troglobite|2}}", re.sub("\\s*\\(iceage_troglobite\\)\\s*", ";<sup>0</sup>;66;{{Troglobite|2}}", re.sub("\\s*\\(iceage_weaselhoarder\\)\\s*", ";<sup>0</sup>;67;{{Weasel Hoarder|2}}", re.sub("\\s*\\(iceage_weasel\\)\\s*", ";<sup>0</sup>;68;{{Ice Weasel|2}}", re.sub("\\s*\\(iceage_gargantuar\\)\\s*", ";<sup>0</sup>;62;{{Sloth Gargantuar|2}}", re.sub("\\s*\\(iceage_imp\\)\\s*", ";<sup>0</sup>;63;{{Yeti Imp|2}}", re.sub("\\s*\\(hellbird\\)\\s*", ";<sup>0</sup>;69{{Zombie Nether Dodo|2}}", tmp3))))))))))))))
    # Lost
    tmp5 = re.sub("\\s*\\(lostcity\\)\\s*", ";<sup>0</sup>;20;{{P|Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_armor1\\)\\s*", ";<sup>0</sup>;21;{{P|Conehead Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_armor2\\)\\s*", ";<sup>0</sup>;22;{{P|Buckethead Adventurer Zombie|2}}", re.sub("\\s*\\(lostcity_excavator\\)\\s*", ";<sup>0</sup>;32;{{P|Excavator Zombie|2}}", re.sub("\\s*\\(lostcity_jane\\)\\s*", ";<sup>0</sup>;25;{{P|Parasol Zombie|2}}", re.sub("\\s*\\(lostcity_lostpilot\\)\\s*", ";<sup>0</sup>;26;{{P|Lost Pilot Zombie|2}}", re.sub("\\s*\\(lostcity_bug\\)\\s*", ";<sup>0</sup>;27;{{P|Bug Zombie|2}}", re.sub("\\s*\\(lostcity_bug_armor1\\)\\s*", ";<sup>0</sup>;28;{{P|Bug Conehead Zombie|2}}", re.sub("\\s*\\(lostcity_bug_armor2\\)\\s*", ";<sup>0</sup>;29;{{P|Bug Buckethead Zombie|2}}", re.sub("\\s*\\(lostcity_impporter\\)\\s*", ";<sup>0</sup>;31;{{P|Imp Porter|2}}", re.sub("\\s*\\(lostcity_relichunter\\)\\s*", ";<sup>0</sup>;33;{{P|Relic Hunter Zombie|2}}", re.sub("\\s*\\(lostcity_crystalskull\\)\\s*", ";<sup>0</sup>;30;{{P|Turquoise Skull Zombie|2}}", re.sub("\\s*\\(lostcity_gargantuar\\)\\s*", ";<sup>0</sup>;23;{{P|Porter Gargantuar|2}}", re.sub("\\s*\\(lostcity_imp\\)\\s*", ";<sup>0</sup>;24;{{P|Lost City Imp Zombie|2}}", re.sub("\\s*\\(lostcity_mime\\)\\s*", ";<sup>0</sup>;14;{{P|Mime Zombie|2}}", tmp4)))))))))))))))
    # Jurassic
    tmp6 = re.sub("\\s*\\(dino\\)\\s*", ";<sup>0</sup>;96;{{P|Jurassic Zombie|2}}", re.sub("\\s*\\(dino_armor1\\)\\s*", ";<sup>0</sup>;97;{{P|Jurassic Conehead|2}}", re.sub("\\s*\\(dino_armor2\\)\\s*", ";<sup>0</sup>;98;{{P|Jurassic Buckethead|2}}", re.sub("\\s*\\(dino_armor3\\)\\s*", ";<sup>0</sup>;99;{{P|Jurassic Fossilhead|2}}", re.sub("\\s*\\(dino_armor4\\)\\s*", ";<sup>0</sup>;100;{{P|Amberhead Zombie|2}}", re.sub("\\s*\\(dino_bully\\)\\s*", ";<sup>0</sup>;103;{{P|Jurassic Bully|2}}", re.sub("\\s*\\(dino_bully_veteran\\)\\s*", ";<sup>0</sup>;103;{{P|Jurassic Bully|2}}", re.sub("\\s*\\(dino_gargantuar\\)\\s*", ";<sup>0</sup>;101;{{P|Jurassic Gargantuar|2}}", re.sub("\\s*\\(dino_imp\\)\\s*", ";<sup>0</sup>;102;{{P|Jurassic Imp|2}}", re.sub("\\s*\\(modern_superfanimp\\)\\s*", ";<sup>0</sup>;104;{{P|Flint imp|2}}", tmp5))))))))))
    # Dinos
    tmp6_5 = re.sub('\\s*\\(raptor\\)\\s*', ';<sup>0</sup>;104.5;Raptor', re.sub('\\s*\\(stego\\)\\s*', ';<sup>0</sup>;104.5;Stegosaurus', re.sub('\\s*\\(ptero\\)\\s*', ';<sup>0</sup>;104.5;Pterodactyl', re.sub('\\s*\\(tyranno\\)\\s*', ';<sup>0</sup>;104.5;Tyrannosaurus Rex', re.sub('\\s*\\(ankylo\\)\\s*', ';<sup>0</sup>;104.5;Ankylosaurus', tmp6)))))
    # Neon
    tmp7 = re.sub("\\s*\\(eighties\\)\\s*", ";<sup>0</sup>;116;{{P|Neon Zombie|2}}", re.sub("\\s*\\(eighties_armor1\\)\\s*", ";<sup>0</sup>;117;{{P|Neon Conehead|2}}", re.sub("\\s*\\(eighties_armor2\\)\\s*", ";<sup>0</sup>;118;{{P|Neon Buckethead|2}}", re.sub("\\s*\\(eighties_punk\\)\\s*", "122;{{P|Punk Zombie|2}}", re.sub("\\s*\\(eighties_glitter\\)\\s*", ";<sup>0</sup>;121;{{P|Glitter Zombie|2}}", re.sub("\\s*\\(eighties_mc\\)\\s*", ";<sup>0</sup>;124;{{P|MC Zom-B|2}}", re.sub("\\s*\\(eighties_breakdancer\\)\\s*", ";<sup>0</sup>;129;{{P|Breakdancer Zombie|2}}", re.sub("\\s*\\(eighties_arcade\\)\\s*", ";<sup>0</sup>;125;{{P|Arcade Zombie|2}}", re.sub("\\s*\\(eighties_8bit\\)\\s*", ";<sup>0</sup>;126;{{P|8-Bit Zombie|2}}", re.sub("\\s*\\(eighties_8bit_armor1\\)\\s*", ";<sup>0</sup>;127;{{P|8-Bit Conehead Zombie|2}}", re.sub("\\s*\\(eighties_8bit_armor2\\)\\s*", ";<sup>0</sup>;128;{{P|8-Bit Buckethead Zombie|2}}", re.sub("\\s*\\(eighties_boombox\\)\\s*", ";<sup>0</sup>;123;{{P|Boombox Zombie|2}}", re.sub("\\s*\\(eighties_gargantuar\\)\\s*", ";<sup>0</sup>;119;{{P|Hair Metal Gargantuar|2}}", re.sub("\\s*\\(eighties_imp\\)\\s*", ";<sup>0</sup>;120;{{P|Impunk|2}}", tmp6_5))))))))))))))
    # Pirate
    tmp8 = re.sub("\\s*\\(pirate\\)\\s*", ";<sup>0</sup>;45;{{P|Pirate Zombie|2}}", re.sub("\\s*\\(pirate_armor1\\)\\s*", ";<sup>0</sup>;46;{{P|Conehead Pirate|2}}", re.sub("\\s*\\(pirate_armor2\\)\\s*", ";<sup>0</sup>;47;{{P|Buckethead Pirate|2}}", re.sub("\\s*\\(pirate_armor4\\)\\s*", ";<sup>0</sup>;48;{{P|Cannonhead Zombie|2}}", re.sub("\\s*\\(swashbuckler\\)\\s*", ";<sup>0</sup>;51;{{P|Swashbuckler Zombie|2}}", re.sub("\\s*\\(seagull\\)\\s*", ";<sup>0</sup>;54;{{P|Seagull Zombie|2}}", re.sub("\\s*\\(pelican\\)\\s*", ";<sup>0</sup>;57;{{P|Pelican Zombie|2}}", re.sub("\\s*\\(barrelroller\\)\\s*", ";<sup>0</sup>;52;{{P|Barrel Roller Zombie|2}}", re.sub("\\s*\\(pirate_barrel\\)\\s*", ";<sup>0</sup>;53;{{P|Pirate Barrel|2}}", re.sub("\\s*\\(cannon\\)\\s*", ";<sup>0</sup>;56;{{P|Imp Cannon|2}}", re.sub("\\s*\\(pirate_captain\\)\\s*", ";<sup>0</sup>;55;{{P|Pirate Captain Zombie|2}}", re.sub("\\s*\\(pirate_gargantuar\\)\\s*", ";<sup>0</sup>;49;{{P|Gargantuar Pirate|2}}", re.sub("\\s*\\(pirate_imp\\)\\s*", ";<sup>0</sup>;50;{{P|Imp Pirate Zombie|2}}", tmp7)))))))))))))
    # West
    tmp9 = re.sub("\\s*\\(cowboy\\)\\s*", ";<sup>0</sup>;70;{{P|Cowboy Zombie|2}}", re.sub("\\s*\\(cowboy_armor1\\)\\s*", ";<sup>0</sup>;71.{{P|Conehead Cowboy|2}}", re.sub("\\s*\\(cowboy_armor2\\)\\s*", ";<sup>0</sup>;72;{{P|Buckethead Cowboy|2}}", re.sub("\\s*\\(cowboy_armor4\\)\\s*", ";<sup>0</sup>;73;{{P|Cart-Head Zombie|2}}", re.sub("\\s*\\(prospector\\)\\s*", ";<sup>0</sup>;76;{{P|Prospector Zombie|2}}", re.sub("\\s*\\(piano\\)\\s*", ";<sup>0</sup>;77;{{P|Pianist Zombie|2}}", re.sub("\\s*\\(poncho\\)\\s*", ";<sup>0</sup>;80;{{P|Vegan Zombie|2}}", re.sub("\\s*\\(poncho_no_plate\\)\\s*", ";<sup>0</sup>;81;{{P|Poncho Zombie|2}}", re.sub("\\s*\\(poncho_plate\\)\\s*", ";<sup>0</sup>;81;{{P|Poncho Zombie|2}}", re.sub("\\s*\\(chicken_farmer\\)\\s*", ";<sup>0</sup>;79;{{P|Chicken Wrangler Zombie|2}}", re.sub("\\s*\\(west_bull\\)\\s*", ";<sup>0</sup>;78;{{P|Zombie Bull|2}}", re.sub("\\s*\\(cowboy_gargantuar\\)\\s*", ";<sup>0</sup>;74;{{P|Wild West Gargantuar|2}}", re.sub("\\s*\\(west_bullrider\\)\\s*", ";<sup>0</sup>;75;{{P|Zombie Bull Rider|2}}", tmp8)))))))))))))

    return tmp9
